### ISSUE TITLE
[Bug]: WYSIWYG Editor Links broken

### ISSUE THREAD

**Issue by Fabian-Hofer-Mastertent** [pimcore/admin-ui-classic-bundle#298] opened 2023-09-27 07:31 UTC
This is a huge bug that broke our hole website. We have a lot of links that are now spanned across the whole content.
Sometimes it breaks the next elements to.

**Pimcore Version:** 11.0.10

**Steps to reproduce:**
You can test the issue in the pimcore Demo: 

1. open a Wysiwyg Editor and add a link. Save and reload the page.
2. The link will be expanded to the end of the paragraph and break all paragraphs after that.

Issue exists with documents AND Data Objects.

I think the problem started with the update to Pimcore 11.0.10

**Comment by dvesh3** [comment] 2023-09-27 07:42
@Fabian-Hofer-Mastertent could you please share reproducible steps? I just tried on demo and it works for me.

**Comment by Fabian-Hofer-Mastertent** [comment] 2023-09-27 07:54
(I think this issue is the same as [https://github.com/pimcore/pimcore/issues/16011](url) so maybe there is no need for this Issue.

Here the steps to reproduce the issue in the Demo Pimcore:

1. i open https://demo.pimcore.com/admin/login/deeplink?document_48_page for example
2. select a text an add a link 
![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/99820683/f5cd0656-f514-4bfe-a1ee-e047f30db8a0)
3. save the popup and save and publish the page (everything looks normal until now)
4. reload the document with the toolbar: now the rest of the text starting with the previously selected link is linked
![image](https://github.com/pimcore/admin-ui-classic-bundle/assets/99820683/1a5327fb-673b-443d-a45a-17c562c4293b)

This broke all links like this on our website for documents and data objects. i had to downgrade pimcore to 11.0.9 to be able to work normally. (but the links that broke with the update are af course still broken and had to to be fixed manually)

**Comment by dvesh3** [comment] 2023-09-27 08:00
Duplicate of https://github.com/pimcore/pimcore/issues/16011

**Closed as completed by dvesh3** 2023-09-27 08:00 UTC
